//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Catalogo", "FK_CatalogoLivros_Autores", "Autores", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Catalogo.Autores), "CatalogoLivros", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Catalogo.CatalogoLivros))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Catalogo", "FK_CatalogoLivros_Categorias", "Categorias", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Catalogo.Categorias), "CatalogoLivros", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Catalogo.CatalogoLivros))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Catalogo", "FK_CatalogoLivros_Editoras", "Editoras", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Catalogo.Editoras), "CatalogoLivros", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Catalogo.CatalogoLivros))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Catalogo", "FK_CatalogoLivros_Usuario", "Usuario", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Catalogo.Usuario), "CatalogoLivros", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Catalogo.CatalogoLivros))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Catalogo", "FK_Usuario_UsuarioPerfil", "UsuarioPerfil", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Catalogo.UsuarioPerfil), "Usuario", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Catalogo.Usuario))]

// Original file name:
// Generation date: 31/7/2010 19:43:58
namespace Catalogo
{
    
    /// <summary>
    /// There are no comments for CatalogoEntities in the schema.
    /// </summary>
    public partial class CatalogoEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new CatalogoEntities object using the connection string found in the 'CatalogoEntities' section of the application configuration file.
        /// </summary>
        public CatalogoEntities() : 
                base("name=CatalogoEntities", "CatalogoEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new CatalogoEntities object.
        /// </summary>
        public CatalogoEntities(string connectionString) : 
                base(connectionString, "CatalogoEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new CatalogoEntities object.
        /// </summary>
        public CatalogoEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "CatalogoEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Autores in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Autores> Autores
        {
            get
            {
                if ((this._Autores == null))
                {
                    this._Autores = base.CreateQuery<Autores>("[Autores]");
                }
                return this._Autores;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Autores> _Autores;
        /// <summary>
        /// There are no comments for CatalogoLivros in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<CatalogoLivros> CatalogoLivros
        {
            get
            {
                if ((this._CatalogoLivros == null))
                {
                    this._CatalogoLivros = base.CreateQuery<CatalogoLivros>("[CatalogoLivros]");
                }
                return this._CatalogoLivros;
            }
        }
        private global::System.Data.Objects.ObjectQuery<CatalogoLivros> _CatalogoLivros;
        /// <summary>
        /// There are no comments for Categorias in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Categorias> Categorias
        {
            get
            {
                if ((this._Categorias == null))
                {
                    this._Categorias = base.CreateQuery<Categorias>("[Categorias]");
                }
                return this._Categorias;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Categorias> _Categorias;
        /// <summary>
        /// There are no comments for Editoras in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Editoras> Editoras
        {
            get
            {
                if ((this._Editoras == null))
                {
                    this._Editoras = base.CreateQuery<Editoras>("[Editoras]");
                }
                return this._Editoras;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Editoras> _Editoras;
        /// <summary>
        /// There are no comments for Usuario in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Usuario> Usuario
        {
            get
            {
                if ((this._Usuario == null))
                {
                    this._Usuario = base.CreateQuery<Usuario>("[Usuario]");
                }
                return this._Usuario;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Usuario> _Usuario;
        /// <summary>
        /// There are no comments for UsuarioPerfil in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<UsuarioPerfil> UsuarioPerfil
        {
            get
            {
                if ((this._UsuarioPerfil == null))
                {
                    this._UsuarioPerfil = base.CreateQuery<UsuarioPerfil>("[UsuarioPerfil]");
                }
                return this._UsuarioPerfil;
            }
        }
        private global::System.Data.Objects.ObjectQuery<UsuarioPerfil> _UsuarioPerfil;
        /// <summary>
        /// There are no comments for Autores in the schema.
        /// </summary>
        public void AddToAutores(Autores autores)
        {
            base.AddObject("Autores", autores);
        }
        /// <summary>
        /// There are no comments for CatalogoLivros in the schema.
        /// </summary>
        public void AddToCatalogoLivros(CatalogoLivros catalogoLivros)
        {
            base.AddObject("CatalogoLivros", catalogoLivros);
        }
        /// <summary>
        /// There are no comments for Categorias in the schema.
        /// </summary>
        public void AddToCategorias(Categorias categorias)
        {
            base.AddObject("Categorias", categorias);
        }
        /// <summary>
        /// There are no comments for Editoras in the schema.
        /// </summary>
        public void AddToEditoras(Editoras editoras)
        {
            base.AddObject("Editoras", editoras);
        }
        /// <summary>
        /// There are no comments for Usuario in the schema.
        /// </summary>
        public void AddToUsuario(Usuario usuario)
        {
            base.AddObject("Usuario", usuario);
        }
        /// <summary>
        /// There are no comments for UsuarioPerfil in the schema.
        /// </summary>
        public void AddToUsuarioPerfil(UsuarioPerfil usuarioPerfil)
        {
            base.AddObject("UsuarioPerfil", usuarioPerfil);
        }
    }
    /// <summary>
    /// There are no comments for Catalogo.Autores in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Catalogo", Name="Autores")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Autores : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Autores object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="nome">Initial value of Nome.</param>
        public static Autores CreateAutores(int id, string nome)
        {
            Autores autores = new Autores();
            autores.ID = id;
            autores.Nome = nome;
            return autores;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Nome in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this._Nome;
            }
            set
            {
                this.OnNomeChanging(value);
                this.ReportPropertyChanging("Nome");
                this._Nome = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Nome");
                this.OnNomeChanged();
            }
        }
        private string _Nome;
        partial void OnNomeChanging(string value);
        partial void OnNomeChanged();
        /// <summary>
        /// There are no comments for CatalogoLivros in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Catalogo", "FK_CatalogoLivros_Autores", "CatalogoLivros")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<CatalogoLivros> CatalogoLivros
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<CatalogoLivros>("Catalogo.FK_CatalogoLivros_Autores", "CatalogoLivros");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<CatalogoLivros>("Catalogo.FK_CatalogoLivros_Autores", "CatalogoLivros", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Catalogo.CatalogoLivros in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Catalogo", Name="CatalogoLivros")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class CatalogoLivros : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new CatalogoLivros object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        public static CatalogoLivros CreateCatalogoLivros(int id)
        {
            CatalogoLivros catalogoLivros = new CatalogoLivros();
            catalogoLivros.ID = id;
            return catalogoLivros;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Titulo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo
        {
            get
            {
                return this._Titulo;
            }
            set
            {
                this.OnTituloChanging(value);
                this.ReportPropertyChanging("Titulo");
                this._Titulo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Titulo");
                this.OnTituloChanged();
            }
        }
        private string _Titulo;
        partial void OnTituloChanging(string value);
        partial void OnTituloChanged();
        /// <summary>
        /// There are no comments for Property Sinopse in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Sinopse
        {
            get
            {
                return this._Sinopse;
            }
            set
            {
                this.OnSinopseChanging(value);
                this.ReportPropertyChanging("Sinopse");
                this._Sinopse = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Sinopse");
                this.OnSinopseChanged();
            }
        }
        private string _Sinopse;
        partial void OnSinopseChanging(string value);
        partial void OnSinopseChanged();
        /// <summary>
        /// There are no comments for Property ISBN in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN
        {
            get
            {
                return this._ISBN;
            }
            set
            {
                this.OnISBNChanging(value);
                this.ReportPropertyChanging("ISBN");
                this._ISBN = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ISBN");
                this.OnISBNChanged();
            }
        }
        private string _ISBN;
        partial void OnISBNChanging(string value);
        partial void OnISBNChanged();
        /// <summary>
        /// There are no comments for Property Edicao in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Edicao
        {
            get
            {
                return this._Edicao;
            }
            set
            {
                this.OnEdicaoChanging(value);
                this.ReportPropertyChanging("Edicao");
                this._Edicao = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Edicao");
                this.OnEdicaoChanged();
            }
        }
        private string _Edicao;
        partial void OnEdicaoChanging(string value);
        partial void OnEdicaoChanged();
        /// <summary>
        /// There are no comments for Property Autor in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Autor
        {
            get
            {
                return this._Autor;
            }
            set
            {
                this.OnAutorChanging(value);
                this.ReportPropertyChanging("Autor");
                this._Autor = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Autor");
                this.OnAutorChanged();
            }
        }
        private string _Autor;
        partial void OnAutorChanging(string value);
        partial void OnAutorChanged();
        /// <summary>
        /// There are no comments for Property Paginas in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Paginas
        {
            get
            {
                return this._Paginas;
            }
            set
            {
                this.OnPaginasChanging(value);
                this.ReportPropertyChanging("Paginas");
                this._Paginas = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Paginas");
                this.OnPaginasChanged();
            }
        }
        private string _Paginas;
        partial void OnPaginasChanging(string value);
        partial void OnPaginasChanged();
        /// <summary>
        /// There are no comments for Property Img in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Img
        {
            get
            {
                return this._Img;
            }
            set
            {
                this.OnImgChanging(value);
                this.ReportPropertyChanging("Img");
                this._Img = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Img");
                this.OnImgChanged();
            }
        }
        private string _Img;
        partial void OnImgChanging(string value);
        partial void OnImgChanged();
        /// <summary>
        /// There are no comments for Property Tags in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Tags
        {
            get
            {
                return this._Tags;
            }
            set
            {
                this.OnTagsChanging(value);
                this.ReportPropertyChanging("Tags");
                this._Tags = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Tags");
                this.OnTagsChanged();
            }
        }
        private string _Tags;
        partial void OnTagsChanging(string value);
        partial void OnTagsChanged();
        /// <summary>
        /// There are no comments for Property Observacao in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacao
        {
            get
            {
                return this._Observacao;
            }
            set
            {
                this.OnObservacaoChanging(value);
                this.ReportPropertyChanging("Observacao");
                this._Observacao = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Observacao");
                this.OnObservacaoChanged();
            }
        }
        private string _Observacao;
        partial void OnObservacaoChanging(string value);
        partial void OnObservacaoChanged();
        /// <summary>
        /// There are no comments for Autores in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Catalogo", "FK_CatalogoLivros_Autores", "Autores")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Autores Autores
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Autores>("Catalogo.FK_CatalogoLivros_Autores", "Autores").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Autores>("Catalogo.FK_CatalogoLivros_Autores", "Autores").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Autores in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Autores> AutoresReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Autores>("Catalogo.FK_CatalogoLivros_Autores", "Autores");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Autores>("Catalogo.FK_CatalogoLivros_Autores", "Autores", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Categorias in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Catalogo", "FK_CatalogoLivros_Categorias", "Categorias")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Categorias Categorias
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Categorias>("Catalogo.FK_CatalogoLivros_Categorias", "Categorias").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Categorias>("Catalogo.FK_CatalogoLivros_Categorias", "Categorias").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Categorias in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Categorias> CategoriasReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Categorias>("Catalogo.FK_CatalogoLivros_Categorias", "Categorias");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Categorias>("Catalogo.FK_CatalogoLivros_Categorias", "Categorias", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Editoras in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Catalogo", "FK_CatalogoLivros_Editoras", "Editoras")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Editoras Editoras
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Editoras>("Catalogo.FK_CatalogoLivros_Editoras", "Editoras").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Editoras>("Catalogo.FK_CatalogoLivros_Editoras", "Editoras").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Editoras in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Editoras> EditorasReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Editoras>("Catalogo.FK_CatalogoLivros_Editoras", "Editoras");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Editoras>("Catalogo.FK_CatalogoLivros_Editoras", "Editoras", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Usuario in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Catalogo", "FK_CatalogoLivros_Usuario", "Usuario")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Usuario Usuario
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Usuario>("Catalogo.FK_CatalogoLivros_Usuario", "Usuario").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Usuario>("Catalogo.FK_CatalogoLivros_Usuario", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Usuario in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Usuario>("Catalogo.FK_CatalogoLivros_Usuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Usuario>("Catalogo.FK_CatalogoLivros_Usuario", "Usuario", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Catalogo.Categorias in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Catalogo", Name="Categorias")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Categorias : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Categorias object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="nome">Initial value of Nome.</param>
        /// <param name="idCatalogoLivros">Initial value of IdCatalogoLivros.</param>
        public static Categorias CreateCategorias(int id, string nome, int idCatalogoLivros)
        {
            Categorias categorias = new Categorias();
            categorias.ID = id;
            categorias.Nome = nome;
            categorias.IdCatalogoLivros = idCatalogoLivros;
            return categorias;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Nome in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this._Nome;
            }
            set
            {
                this.OnNomeChanging(value);
                this.ReportPropertyChanging("Nome");
                this._Nome = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Nome");
                this.OnNomeChanged();
            }
        }
        private string _Nome;
        partial void OnNomeChanging(string value);
        partial void OnNomeChanged();
        /// <summary>
        /// There are no comments for Property IdCatalogoLivros in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCatalogoLivros
        {
            get
            {
                return this._IdCatalogoLivros;
            }
            set
            {
                this.OnIdCatalogoLivrosChanging(value);
                this.ReportPropertyChanging("IdCatalogoLivros");
                this._IdCatalogoLivros = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdCatalogoLivros");
                this.OnIdCatalogoLivrosChanged();
            }
        }
        private int _IdCatalogoLivros;
        partial void OnIdCatalogoLivrosChanging(int value);
        partial void OnIdCatalogoLivrosChanged();
        /// <summary>
        /// There are no comments for CatalogoLivros in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Catalogo", "FK_CatalogoLivros_Categorias", "CatalogoLivros")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<CatalogoLivros> CatalogoLivros
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<CatalogoLivros>("Catalogo.FK_CatalogoLivros_Categorias", "CatalogoLivros");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<CatalogoLivros>("Catalogo.FK_CatalogoLivros_Categorias", "CatalogoLivros", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Catalogo.Editoras in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Catalogo", Name="Editoras")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Editoras : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Editoras object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="nome">Initial value of Nome.</param>
        public static Editoras CreateEditoras(int id, string nome)
        {
            Editoras editoras = new Editoras();
            editoras.ID = id;
            editoras.Nome = nome;
            return editoras;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Nome in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this._Nome;
            }
            set
            {
                this.OnNomeChanging(value);
                this.ReportPropertyChanging("Nome");
                this._Nome = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Nome");
                this.OnNomeChanged();
            }
        }
        private string _Nome;
        partial void OnNomeChanging(string value);
        partial void OnNomeChanged();
        /// <summary>
        /// There are no comments for CatalogoLivros in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Catalogo", "FK_CatalogoLivros_Editoras", "CatalogoLivros")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<CatalogoLivros> CatalogoLivros
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<CatalogoLivros>("Catalogo.FK_CatalogoLivros_Editoras", "CatalogoLivros");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<CatalogoLivros>("Catalogo.FK_CatalogoLivros_Editoras", "CatalogoLivros", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Catalogo.Usuario in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Catalogo", Name="Usuario")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Usuario : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="nome">Initial value of nome.</param>
        /// <param name="email">Initial value of Email.</param>
        /// <param name="senha">Initial value of Senha.</param>
        /// <param name="deletado">Initial value of Deletado.</param>
        public static Usuario CreateUsuario(int id, string nome, string email, string senha, bool deletado)
        {
            Usuario usuario = new Usuario();
            usuario.ID = id;
            usuario.nome = nome;
            usuario.Email = email;
            usuario.Senha = senha;
            usuario.Deletado = deletado;
            return usuario;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property nome in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string nome
        {
            get
            {
                return this._nome;
            }
            set
            {
                this.OnnomeChanging(value);
                this.ReportPropertyChanging("nome");
                this._nome = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("nome");
                this.OnnomeChanged();
            }
        }
        private string _nome;
        partial void OnnomeChanging(string value);
        partial void OnnomeChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this.ReportPropertyChanging("Email");
                this._Email = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Email");
                this.OnEmailChanged();
            }
        }
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property Senha in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha
        {
            get
            {
                return this._Senha;
            }
            set
            {
                this.OnSenhaChanging(value);
                this.ReportPropertyChanging("Senha");
                this._Senha = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Senha");
                this.OnSenhaChanged();
            }
        }
        private string _Senha;
        partial void OnSenhaChanging(string value);
        partial void OnSenhaChanged();
        /// <summary>
        /// There are no comments for Property Deletado in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deletado
        {
            get
            {
                return this._Deletado;
            }
            set
            {
                this.OnDeletadoChanging(value);
                this.ReportPropertyChanging("Deletado");
                this._Deletado = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Deletado");
                this.OnDeletadoChanged();
            }
        }
        private bool _Deletado;
        partial void OnDeletadoChanging(bool value);
        partial void OnDeletadoChanged();
        /// <summary>
        /// There are no comments for CatalogoLivros in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Catalogo", "FK_CatalogoLivros_Usuario", "CatalogoLivros")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<CatalogoLivros> CatalogoLivros
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<CatalogoLivros>("Catalogo.FK_CatalogoLivros_Usuario", "CatalogoLivros");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<CatalogoLivros>("Catalogo.FK_CatalogoLivros_Usuario", "CatalogoLivros", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for UsuarioPerfil in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Catalogo", "FK_Usuario_UsuarioPerfil", "UsuarioPerfil")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public UsuarioPerfil UsuarioPerfil
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<UsuarioPerfil>("Catalogo.FK_Usuario_UsuarioPerfil", "UsuarioPerfil").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<UsuarioPerfil>("Catalogo.FK_Usuario_UsuarioPerfil", "UsuarioPerfil").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for UsuarioPerfil in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<UsuarioPerfil> UsuarioPerfilReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<UsuarioPerfil>("Catalogo.FK_Usuario_UsuarioPerfil", "UsuarioPerfil");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<UsuarioPerfil>("Catalogo.FK_Usuario_UsuarioPerfil", "UsuarioPerfil", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Catalogo.UsuarioPerfil in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Catalogo", Name="UsuarioPerfil")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class UsuarioPerfil : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new UsuarioPerfil object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="perfil">Initial value of Perfil.</param>
        public static UsuarioPerfil CreateUsuarioPerfil(int id, string perfil)
        {
            UsuarioPerfil usuarioPerfil = new UsuarioPerfil();
            usuarioPerfil.ID = id;
            usuarioPerfil.Perfil = perfil;
            return usuarioPerfil;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Perfil in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Perfil
        {
            get
            {
                return this._Perfil;
            }
            set
            {
                this.OnPerfilChanging(value);
                this.ReportPropertyChanging("Perfil");
                this._Perfil = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Perfil");
                this.OnPerfilChanged();
            }
        }
        private string _Perfil;
        partial void OnPerfilChanging(string value);
        partial void OnPerfilChanged();
        /// <summary>
        /// There are no comments for Usuario in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Catalogo", "FK_Usuario_UsuarioPerfil", "Usuario")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Usuario> Usuario
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Usuario>("Catalogo.FK_Usuario_UsuarioPerfil", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Usuario>("Catalogo.FK_Usuario_UsuarioPerfil", "Usuario", value);
                }
            }
        }
    }
}
