//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Catalogo", "FK_CatalogoLivros_Autores", "Autores", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Catalogo.Autores), "CatalogoLivros", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Catalogo.CatalogoLivros))]
[assembly: EdmRelationshipAttribute("Catalogo", "FK_CatalogoLivros_Categorias", "Categorias", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Catalogo.Categorias), "CatalogoLivros", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Catalogo.CatalogoLivros))]
[assembly: EdmRelationshipAttribute("Catalogo", "FK_CatalogoLivros_Editoras", "Editoras", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Catalogo.Editoras), "CatalogoLivros", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Catalogo.CatalogoLivros))]
[assembly: EdmRelationshipAttribute("Catalogo", "FK_CatalogoLivros_Usuario", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Catalogo.Usuario), "CatalogoLivros", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Catalogo.CatalogoLivros))]
[assembly: EdmRelationshipAttribute("Catalogo", "FK_Usuario_UsuarioPerfil", "UsuarioPerfil", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Catalogo.UsuarioPerfil), "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Catalogo.Usuario))]

#endregion

namespace Catalogo
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CatalogoEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CatalogoEntities object using the connection string found in the 'CatalogoEntities' section of the application configuration file.
        /// </summary>
        public CatalogoEntities() : base("name=CatalogoEntities", "CatalogoEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CatalogoEntities object.
        /// </summary>
        public CatalogoEntities(string connectionString) : base(connectionString, "CatalogoEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CatalogoEntities object.
        /// </summary>
        public CatalogoEntities(EntityConnection connection) : base(connection, "CatalogoEntities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Autores> Autores
        {
            get
            {
                if ((_Autores == null))
                {
                    _Autores = base.CreateObjectSet<Autores>("Autores");
                }
                return _Autores;
            }
        }
        private ObjectSet<Autores> _Autores;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CatalogoLivros> CatalogoLivros
        {
            get
            {
                if ((_CatalogoLivros == null))
                {
                    _CatalogoLivros = base.CreateObjectSet<CatalogoLivros>("CatalogoLivros");
                }
                return _CatalogoLivros;
            }
        }
        private ObjectSet<CatalogoLivros> _CatalogoLivros;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Categorias> Categorias
        {
            get
            {
                if ((_Categorias == null))
                {
                    _Categorias = base.CreateObjectSet<Categorias>("Categorias");
                }
                return _Categorias;
            }
        }
        private ObjectSet<Categorias> _Categorias;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Editoras> Editoras
        {
            get
            {
                if ((_Editoras == null))
                {
                    _Editoras = base.CreateObjectSet<Editoras>("Editoras");
                }
                return _Editoras;
            }
        }
        private ObjectSet<Editoras> _Editoras;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> Usuario
        {
            get
            {
                if ((_Usuario == null))
                {
                    _Usuario = base.CreateObjectSet<Usuario>("Usuario");
                }
                return _Usuario;
            }
        }
        private ObjectSet<Usuario> _Usuario;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UsuarioPerfil> UsuarioPerfil
        {
            get
            {
                if ((_UsuarioPerfil == null))
                {
                    _UsuarioPerfil = base.CreateObjectSet<UsuarioPerfil>("UsuarioPerfil");
                }
                return _UsuarioPerfil;
            }
        }
        private ObjectSet<UsuarioPerfil> _UsuarioPerfil;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Autores EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAutores(Autores autores)
        {
            base.AddObject("Autores", autores);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CatalogoLivros EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCatalogoLivros(CatalogoLivros catalogoLivros)
        {
            base.AddObject("CatalogoLivros", catalogoLivros);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categorias EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategorias(Categorias categorias)
        {
            base.AddObject("Categorias", categorias);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Editoras EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEditoras(Editoras editoras)
        {
            base.AddObject("Editoras", editoras);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuario(Usuario usuario)
        {
            base.AddObject("Usuario", usuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UsuarioPerfil EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarioPerfil(UsuarioPerfil usuarioPerfil)
        {
            base.AddObject("UsuarioPerfil", usuarioPerfil);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Catalogo", Name="Autores")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Autores : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Autores object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        public static Autores CreateAutores(global::System.Int32 id, global::System.String nome)
        {
            Autores autores = new Autores();
            autores.ID = id;
            autores.Nome = nome;
            return autores;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Catalogo", "FK_CatalogoLivros_Autores", "CatalogoLivros")]
        public EntityCollection<CatalogoLivros> CatalogoLivros
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CatalogoLivros>("Catalogo.FK_CatalogoLivros_Autores", "CatalogoLivros");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CatalogoLivros>("Catalogo.FK_CatalogoLivros_Autores", "CatalogoLivros", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Catalogo", Name="CatalogoLivros")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CatalogoLivros : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CatalogoLivros object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static CatalogoLivros CreateCatalogoLivros(global::System.Int32 id)
        {
            CatalogoLivros catalogoLivros = new CatalogoLivros();
            catalogoLivros.ID = id;
            return catalogoLivros;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sinopse
        {
            get
            {
                return _Sinopse;
            }
            set
            {
                OnSinopseChanging(value);
                ReportPropertyChanging("Sinopse");
                _Sinopse = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sinopse");
                OnSinopseChanged();
            }
        }
        private global::System.String _Sinopse;
        partial void OnSinopseChanging(global::System.String value);
        partial void OnSinopseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ISBN
        {
            get
            {
                return _ISBN;
            }
            set
            {
                OnISBNChanging(value);
                ReportPropertyChanging("ISBN");
                _ISBN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ISBN");
                OnISBNChanged();
            }
        }
        private global::System.String _ISBN;
        partial void OnISBNChanging(global::System.String value);
        partial void OnISBNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Edicao
        {
            get
            {
                return _Edicao;
            }
            set
            {
                OnEdicaoChanging(value);
                ReportPropertyChanging("Edicao");
                _Edicao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Edicao");
                OnEdicaoChanged();
            }
        }
        private global::System.String _Edicao;
        partial void OnEdicaoChanging(global::System.String value);
        partial void OnEdicaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Autor
        {
            get
            {
                return _Autor;
            }
            set
            {
                OnAutorChanging(value);
                ReportPropertyChanging("Autor");
                _Autor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Autor");
                OnAutorChanged();
            }
        }
        private global::System.String _Autor;
        partial void OnAutorChanging(global::System.String value);
        partial void OnAutorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Paginas
        {
            get
            {
                return _Paginas;
            }
            set
            {
                OnPaginasChanging(value);
                ReportPropertyChanging("Paginas");
                _Paginas = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Paginas");
                OnPaginasChanged();
            }
        }
        private global::System.String _Paginas;
        partial void OnPaginasChanging(global::System.String value);
        partial void OnPaginasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Img
        {
            get
            {
                return _Img;
            }
            set
            {
                OnImgChanging(value);
                ReportPropertyChanging("Img");
                _Img = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Img");
                OnImgChanged();
            }
        }
        private global::System.String _Img;
        partial void OnImgChanging(global::System.String value);
        partial void OnImgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tags
        {
            get
            {
                return _Tags;
            }
            set
            {
                OnTagsChanging(value);
                ReportPropertyChanging("Tags");
                _Tags = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tags");
                OnTagsChanged();
            }
        }
        private global::System.String _Tags;
        partial void OnTagsChanging(global::System.String value);
        partial void OnTagsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Observacao
        {
            get
            {
                return _Observacao;
            }
            set
            {
                OnObservacaoChanging(value);
                ReportPropertyChanging("Observacao");
                _Observacao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Observacao");
                OnObservacaoChanged();
            }
        }
        private global::System.String _Observacao;
        partial void OnObservacaoChanging(global::System.String value);
        partial void OnObservacaoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Catalogo", "FK_CatalogoLivros_Autores", "Autores")]
        public Autores Autores
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Autores>("Catalogo.FK_CatalogoLivros_Autores", "Autores").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Autores>("Catalogo.FK_CatalogoLivros_Autores", "Autores").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Autores> AutoresReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Autores>("Catalogo.FK_CatalogoLivros_Autores", "Autores");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Autores>("Catalogo.FK_CatalogoLivros_Autores", "Autores", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Catalogo", "FK_CatalogoLivros_Categorias", "Categorias")]
        public Categorias Categorias
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categorias>("Catalogo.FK_CatalogoLivros_Categorias", "Categorias").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categorias>("Catalogo.FK_CatalogoLivros_Categorias", "Categorias").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Categorias> CategoriasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categorias>("Catalogo.FK_CatalogoLivros_Categorias", "Categorias");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Categorias>("Catalogo.FK_CatalogoLivros_Categorias", "Categorias", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Catalogo", "FK_CatalogoLivros_Editoras", "Editoras")]
        public Editoras Editoras
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Editoras>("Catalogo.FK_CatalogoLivros_Editoras", "Editoras").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Editoras>("Catalogo.FK_CatalogoLivros_Editoras", "Editoras").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Editoras> EditorasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Editoras>("Catalogo.FK_CatalogoLivros_Editoras", "Editoras");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Editoras>("Catalogo.FK_CatalogoLivros_Editoras", "Editoras", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Catalogo", "FK_CatalogoLivros_Usuario", "Usuario")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("Catalogo.FK_CatalogoLivros_Usuario", "Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("Catalogo.FK_CatalogoLivros_Usuario", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("Catalogo.FK_CatalogoLivros_Usuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("Catalogo.FK_CatalogoLivros_Usuario", "Usuario", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Catalogo", Name="Categorias")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Categorias : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Categorias object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="idCatalogoLivros">Initial value of the IdCatalogoLivros property.</param>
        public static Categorias CreateCategorias(global::System.Int32 id, global::System.String nome, global::System.Int32 idCatalogoLivros)
        {
            Categorias categorias = new Categorias();
            categorias.ID = id;
            categorias.Nome = nome;
            categorias.IdCatalogoLivros = idCatalogoLivros;
            return categorias;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCatalogoLivros
        {
            get
            {
                return _IdCatalogoLivros;
            }
            set
            {
                OnIdCatalogoLivrosChanging(value);
                ReportPropertyChanging("IdCatalogoLivros");
                _IdCatalogoLivros = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdCatalogoLivros");
                OnIdCatalogoLivrosChanged();
            }
        }
        private global::System.Int32 _IdCatalogoLivros;
        partial void OnIdCatalogoLivrosChanging(global::System.Int32 value);
        partial void OnIdCatalogoLivrosChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Catalogo", "FK_CatalogoLivros_Categorias", "CatalogoLivros")]
        public EntityCollection<CatalogoLivros> CatalogoLivros
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CatalogoLivros>("Catalogo.FK_CatalogoLivros_Categorias", "CatalogoLivros");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CatalogoLivros>("Catalogo.FK_CatalogoLivros_Categorias", "CatalogoLivros", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Catalogo", Name="Editoras")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Editoras : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Editoras object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        public static Editoras CreateEditoras(global::System.Int32 id, global::System.String nome)
        {
            Editoras editoras = new Editoras();
            editoras.ID = id;
            editoras.Nome = nome;
            return editoras;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Catalogo", "FK_CatalogoLivros_Editoras", "CatalogoLivros")]
        public EntityCollection<CatalogoLivros> CatalogoLivros
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CatalogoLivros>("Catalogo.FK_CatalogoLivros_Editoras", "CatalogoLivros");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CatalogoLivros>("Catalogo.FK_CatalogoLivros_Editoras", "CatalogoLivros", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Catalogo", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="nome">Initial value of the nome property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="senha">Initial value of the Senha property.</param>
        /// <param name="deletado">Initial value of the Deletado property.</param>
        public static Usuario CreateUsuario(global::System.Int32 id, global::System.String nome, global::System.String email, global::System.String senha, global::System.Boolean deletado)
        {
            Usuario usuario = new Usuario();
            usuario.ID = id;
            usuario.nome = nome;
            usuario.Email = email;
            usuario.Senha = senha;
            usuario.Deletado = deletado;
            return usuario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Senha
        {
            get
            {
                return _Senha;
            }
            set
            {
                OnSenhaChanging(value);
                ReportPropertyChanging("Senha");
                _Senha = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Senha");
                OnSenhaChanged();
            }
        }
        private global::System.String _Senha;
        partial void OnSenhaChanging(global::System.String value);
        partial void OnSenhaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Deletado
        {
            get
            {
                return _Deletado;
            }
            set
            {
                OnDeletadoChanging(value);
                ReportPropertyChanging("Deletado");
                _Deletado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Deletado");
                OnDeletadoChanged();
            }
        }
        private global::System.Boolean _Deletado;
        partial void OnDeletadoChanging(global::System.Boolean value);
        partial void OnDeletadoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Catalogo", "FK_CatalogoLivros_Usuario", "CatalogoLivros")]
        public EntityCollection<CatalogoLivros> CatalogoLivros
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CatalogoLivros>("Catalogo.FK_CatalogoLivros_Usuario", "CatalogoLivros");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CatalogoLivros>("Catalogo.FK_CatalogoLivros_Usuario", "CatalogoLivros", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Catalogo", "FK_Usuario_UsuarioPerfil", "UsuarioPerfil")]
        public UsuarioPerfil UsuarioPerfil
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsuarioPerfil>("Catalogo.FK_Usuario_UsuarioPerfil", "UsuarioPerfil").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsuarioPerfil>("Catalogo.FK_Usuario_UsuarioPerfil", "UsuarioPerfil").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UsuarioPerfil> UsuarioPerfilReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsuarioPerfil>("Catalogo.FK_Usuario_UsuarioPerfil", "UsuarioPerfil");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UsuarioPerfil>("Catalogo.FK_Usuario_UsuarioPerfil", "UsuarioPerfil", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Catalogo", Name="UsuarioPerfil")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UsuarioPerfil : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UsuarioPerfil object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="perfil">Initial value of the Perfil property.</param>
        public static UsuarioPerfil CreateUsuarioPerfil(global::System.Int32 id, global::System.String perfil)
        {
            UsuarioPerfil usuarioPerfil = new UsuarioPerfil();
            usuarioPerfil.ID = id;
            usuarioPerfil.Perfil = perfil;
            return usuarioPerfil;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Perfil
        {
            get
            {
                return _Perfil;
            }
            set
            {
                OnPerfilChanging(value);
                ReportPropertyChanging("Perfil");
                _Perfil = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Perfil");
                OnPerfilChanged();
            }
        }
        private global::System.String _Perfil;
        partial void OnPerfilChanging(global::System.String value);
        partial void OnPerfilChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Catalogo", "FK_Usuario_UsuarioPerfil", "Usuario")]
        public EntityCollection<Usuario> Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Usuario>("Catalogo.FK_Usuario_UsuarioPerfil", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Usuario>("Catalogo.FK_Usuario_UsuarioPerfil", "Usuario", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
