//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("stiperModel", "Id", "evento", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(stiperModel.evento), "eventocadastro", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(stiperModel.eventocadastro), true)]

#endregion

namespace stiperModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entidades : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entidades object using the connection string found in the 'Entidades' section of the application configuration file.
        /// </summary>
        public Entidades() : base("name=Entidades", "Entidades")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entidades object.
        /// </summary>
        public Entidades(string connectionString) : base(connectionString, "Entidades")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entidades object.
        /// </summary>
        public Entidades(EntityConnection connection) : base(connection, "Entidades")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<evento> evento
        {
            get
            {
                if ((_evento == null))
                {
                    _evento = base.CreateObjectSet<evento>("evento");
                }
                return _evento;
            }
        }
        private ObjectSet<evento> _evento;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<eventocadastro> eventocadastro
        {
            get
            {
                if ((_eventocadastro == null))
                {
                    _eventocadastro = base.CreateObjectSet<eventocadastro>("eventocadastro");
                }
                return _eventocadastro;
            }
        }
        private ObjectSet<eventocadastro> _eventocadastro;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<revendedorpf> revendedorpf
        {
            get
            {
                if ((_revendedorpf == null))
                {
                    _revendedorpf = base.CreateObjectSet<revendedorpf>("revendedorpf");
                }
                return _revendedorpf;
            }
        }
        private ObjectSet<revendedorpf> _revendedorpf;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<revendedorpj> revendedorpj
        {
            get
            {
                if ((_revendedorpj == null))
                {
                    _revendedorpj = base.CreateObjectSet<revendedorpj>("revendedorpj");
                }
                return _revendedorpj;
            }
        }
        private ObjectSet<revendedorpj> _revendedorpj;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the evento EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToevento(evento evento)
        {
            base.AddObject("evento", evento);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the eventocadastro EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToeventocadastro(eventocadastro eventocadastro)
        {
            base.AddObject("eventocadastro", eventocadastro);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the revendedorpf EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorevendedorpf(revendedorpf revendedorpf)
        {
            base.AddObject("revendedorpf", revendedorpf);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the revendedorpj EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorevendedorpj(revendedorpj revendedorpj)
        {
            base.AddObject("revendedorpj", revendedorpj);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="stiperModel", Name="evento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class evento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new evento object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static evento Createevento(global::System.Int32 id)
        {
            evento evento = new evento();
            evento.Id = id;
            return evento;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Bairro
        {
            get
            {
                return _Bairro;
            }
            set
            {
                OnBairroChanging(value);
                ReportPropertyChanging("Bairro");
                _Bairro = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Bairro");
                OnBairroChanged();
            }
        }
        private global::System.String _Bairro;
        partial void OnBairroChanging(global::System.String value);
        partial void OnBairroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CEP
        {
            get
            {
                return _CEP;
            }
            set
            {
                OnCEPChanging(value);
                ReportPropertyChanging("CEP");
                _CEP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CEP");
                OnCEPChanged();
            }
        }
        private global::System.String _CEP;
        partial void OnCEPChanging(global::System.String value);
        partial void OnCEPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cidade
        {
            get
            {
                return _Cidade;
            }
            set
            {
                OnCidadeChanging(value);
                ReportPropertyChanging("Cidade");
                _Cidade = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cidade");
                OnCidadeChanged();
            }
        }
        private global::System.String _Cidade;
        partial void OnCidadeChanging(global::System.String value);
        partial void OnCidadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Data
        {
            get
            {
                return _Data;
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private Nullable<global::System.DateTime> _Data;
        partial void OnDataChanging(Nullable<global::System.DateTime> value);
        partial void OnDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Endereco
        {
            get
            {
                return _Endereco;
            }
            set
            {
                OnEnderecoChanging(value);
                ReportPropertyChanging("Endereco");
                _Endereco = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Endereco");
                OnEnderecoChanged();
            }
        }
        private global::System.String _Endereco;
        partial void OnEnderecoChanging(global::System.String value);
        partial void OnEnderecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Gratuito
        {
            get
            {
                return _Gratuito;
            }
            set
            {
                OnGratuitoChanging(value);
                ReportPropertyChanging("Gratuito");
                _Gratuito = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Gratuito");
                OnGratuitoChanged();
            }
        }
        private Nullable<global::System.Int32> _Gratuito;
        partial void OnGratuitoChanging(Nullable<global::System.Int32> value);
        partial void OnGratuitoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HoraInicio
        {
            get
            {
                return _HoraInicio;
            }
            set
            {
                OnHoraInicioChanging(value);
                ReportPropertyChanging("HoraInicio");
                _HoraInicio = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HoraInicio");
                OnHoraInicioChanged();
            }
        }
        private global::System.String _HoraInicio;
        partial void OnHoraInicioChanging(global::System.String value);
        partial void OnHoraInicioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HoraTermino
        {
            get
            {
                return _HoraTermino;
            }
            set
            {
                OnHoraTerminoChanging(value);
                ReportPropertyChanging("HoraTermino");
                _HoraTermino = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HoraTermino");
                OnHoraTerminoChanged();
            }
        }
        private global::System.String _HoraTermino;
        partial void OnHoraTerminoChanging(global::System.String value);
        partial void OnHoraTerminoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UF
        {
            get
            {
                return _UF;
            }
            set
            {
                OnUFChanging(value);
                ReportPropertyChanging("UF");
                _UF = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UF");
                OnUFChanged();
            }
        }
        private global::System.String _UF;
        partial void OnUFChanging(global::System.String value);
        partial void OnUFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Valor
        {
            get
            {
                return _Valor;
            }
            set
            {
                OnValorChanging(value);
                ReportPropertyChanging("Valor");
                _Valor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Valor");
                OnValorChanged();
            }
        }
        private global::System.String _Valor;
        partial void OnValorChanging(global::System.String value);
        partial void OnValorChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("stiperModel", "Id", "eventocadastro")]
        public EntityCollection<eventocadastro> eventocadastro
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<eventocadastro>("stiperModel.Id", "eventocadastro");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<eventocadastro>("stiperModel.Id", "eventocadastro", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="stiperModel", Name="eventocadastro")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class eventocadastro : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new eventocadastro object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="idEvento">Initial value of the IdEvento property.</param>
        public static eventocadastro Createeventocadastro(global::System.Int32 id, global::System.Int32 idEvento)
        {
            eventocadastro eventocadastro = new eventocadastro();
            eventocadastro.Id = id;
            eventocadastro.IdEvento = idEvento;
            return eventocadastro;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AreaAtuacao
        {
            get
            {
                return _AreaAtuacao;
            }
            set
            {
                OnAreaAtuacaoChanging(value);
                ReportPropertyChanging("AreaAtuacao");
                _AreaAtuacao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AreaAtuacao");
                OnAreaAtuacaoChanged();
            }
        }
        private global::System.String _AreaAtuacao;
        partial void OnAreaAtuacaoChanging(global::System.String value);
        partial void OnAreaAtuacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Bairro
        {
            get
            {
                return _Bairro;
            }
            set
            {
                OnBairroChanging(value);
                ReportPropertyChanging("Bairro");
                _Bairro = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Bairro");
                OnBairroChanged();
            }
        }
        private global::System.String _Bairro;
        partial void OnBairroChanging(global::System.String value);
        partial void OnBairroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CEP
        {
            get
            {
                return _CEP;
            }
            set
            {
                OnCEPChanging(value);
                ReportPropertyChanging("CEP");
                _CEP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CEP");
                OnCEPChanged();
            }
        }
        private global::System.String _CEP;
        partial void OnCEPChanging(global::System.String value);
        partial void OnCEPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cidade
        {
            get
            {
                return _Cidade;
            }
            set
            {
                OnCidadeChanging(value);
                ReportPropertyChanging("Cidade");
                _Cidade = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cidade");
                OnCidadeChanged();
            }
        }
        private global::System.String _Cidade;
        partial void OnCidadeChanging(global::System.String value);
        partial void OnCidadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CPF_CNPJ
        {
            get
            {
                return _CPF_CNPJ;
            }
            set
            {
                OnCPF_CNPJChanging(value);
                ReportPropertyChanging("CPF_CNPJ");
                _CPF_CNPJ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CPF_CNPJ");
                OnCPF_CNPJChanged();
            }
        }
        private global::System.String _CPF_CNPJ;
        partial void OnCPF_CNPJChanging(global::System.String value);
        partial void OnCPF_CNPJChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Endereco
        {
            get
            {
                return _Endereco;
            }
            set
            {
                OnEnderecoChanging(value);
                ReportPropertyChanging("Endereco");
                _Endereco = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Endereco");
                OnEnderecoChanged();
            }
        }
        private global::System.String _Endereco;
        partial void OnEnderecoChanging(global::System.String value);
        partial void OnEnderecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEvento
        {
            get
            {
                return _IdEvento;
            }
            set
            {
                OnIdEventoChanging(value);
                ReportPropertyChanging("IdEvento");
                _IdEvento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEvento");
                OnIdEventoChanged();
            }
        }
        private global::System.Int32 _IdEvento;
        partial void OnIdEventoChanging(global::System.Int32 value);
        partial void OnIdEventoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Observacao
        {
            get
            {
                return _Observacao;
            }
            set
            {
                OnObservacaoChanging(value);
                ReportPropertyChanging("Observacao");
                _Observacao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Observacao");
                OnObservacaoChanged();
            }
        }
        private global::System.String _Observacao;
        partial void OnObservacaoChanging(global::System.String value);
        partial void OnObservacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefone01
        {
            get
            {
                return _Telefone01;
            }
            set
            {
                OnTelefone01Changing(value);
                ReportPropertyChanging("Telefone01");
                _Telefone01 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefone01");
                OnTelefone01Changed();
            }
        }
        private global::System.String _Telefone01;
        partial void OnTelefone01Changing(global::System.String value);
        partial void OnTelefone01Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefone02
        {
            get
            {
                return _Telefone02;
            }
            set
            {
                OnTelefone02Changing(value);
                ReportPropertyChanging("Telefone02");
                _Telefone02 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefone02");
                OnTelefone02Changed();
            }
        }
        private global::System.String _Telefone02;
        partial void OnTelefone02Changing(global::System.String value);
        partial void OnTelefone02Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UF
        {
            get
            {
                return _UF;
            }
            set
            {
                OnUFChanging(value);
                ReportPropertyChanging("UF");
                _UF = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UF");
                OnUFChanged();
            }
        }
        private global::System.String _UF;
        partial void OnUFChanging(global::System.String value);
        partial void OnUFChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("stiperModel", "Id", "evento")]
        public evento evento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<evento>("stiperModel.Id", "evento").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<evento>("stiperModel.Id", "evento").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<evento> eventoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<evento>("stiperModel.Id", "evento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<evento>("stiperModel.Id", "evento", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="stiperModel", Name="revendedorpf")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class revendedorpf : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new revendedorpf object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static revendedorpf Createrevendedorpf(global::System.Int32 id)
        {
            revendedorpf revendedorpf = new revendedorpf();
            revendedorpf.Id = id;
            return revendedorpf;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AtividadesAtuais
        {
            get
            {
                return _AtividadesAtuais;
            }
            set
            {
                OnAtividadesAtuaisChanging(value);
                ReportPropertyChanging("AtividadesAtuais");
                _AtividadesAtuais = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AtividadesAtuais");
                OnAtividadesAtuaisChanged();
            }
        }
        private global::System.String _AtividadesAtuais;
        partial void OnAtividadesAtuaisChanging(global::System.String value);
        partial void OnAtividadesAtuaisChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BairroComercial
        {
            get
            {
                return _BairroComercial;
            }
            set
            {
                OnBairroComercialChanging(value);
                ReportPropertyChanging("BairroComercial");
                _BairroComercial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BairroComercial");
                OnBairroComercialChanged();
            }
        }
        private global::System.String _BairroComercial;
        partial void OnBairroComercialChanging(global::System.String value);
        partial void OnBairroComercialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BairroResidencial
        {
            get
            {
                return _BairroResidencial;
            }
            set
            {
                OnBairroResidencialChanging(value);
                ReportPropertyChanging("BairroResidencial");
                _BairroResidencial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BairroResidencial");
                OnBairroResidencialChanged();
            }
        }
        private global::System.String _BairroResidencial;
        partial void OnBairroResidencialChanging(global::System.String value);
        partial void OnBairroResidencialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CEPComercial
        {
            get
            {
                return _CEPComercial;
            }
            set
            {
                OnCEPComercialChanging(value);
                ReportPropertyChanging("CEPComercial");
                _CEPComercial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CEPComercial");
                OnCEPComercialChanged();
            }
        }
        private global::System.String _CEPComercial;
        partial void OnCEPComercialChanging(global::System.String value);
        partial void OnCEPComercialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CEPResidecial
        {
            get
            {
                return _CEPResidecial;
            }
            set
            {
                OnCEPResidecialChanging(value);
                ReportPropertyChanging("CEPResidecial");
                _CEPResidecial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CEPResidecial");
                OnCEPResidecialChanged();
            }
        }
        private global::System.String _CEPResidecial;
        partial void OnCEPResidecialChanging(global::System.String value);
        partial void OnCEPResidecialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CidadeComercial
        {
            get
            {
                return _CidadeComercial;
            }
            set
            {
                OnCidadeComercialChanging(value);
                ReportPropertyChanging("CidadeComercial");
                _CidadeComercial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CidadeComercial");
                OnCidadeComercialChanged();
            }
        }
        private global::System.String _CidadeComercial;
        partial void OnCidadeComercialChanging(global::System.String value);
        partial void OnCidadeComercialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CidadeResidencial
        {
            get
            {
                return _CidadeResidencial;
            }
            set
            {
                OnCidadeResidencialChanging(value);
                ReportPropertyChanging("CidadeResidencial");
                _CidadeResidencial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CidadeResidencial");
                OnCidadeResidencialChanged();
            }
        }
        private global::System.String _CidadeResidencial;
        partial void OnCidadeResidencialChanging(global::System.String value);
        partial void OnCidadeResidencialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CPF
        {
            get
            {
                return _CPF;
            }
            set
            {
                OnCPFChanging(value);
                ReportPropertyChanging("CPF");
                _CPF = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CPF");
                OnCPFChanged();
            }
        }
        private global::System.String _CPF;
        partial void OnCPFChanging(global::System.String value);
        partial void OnCPFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Curriculo
        {
            get
            {
                return _Curriculo;
            }
            set
            {
                OnCurriculoChanging(value);
                ReportPropertyChanging("Curriculo");
                _Curriculo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Curriculo");
                OnCurriculoChanged();
            }
        }
        private global::System.String _Curriculo;
        partial void OnCurriculoChanging(global::System.String value);
        partial void OnCurriculoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email01
        {
            get
            {
                return _Email01;
            }
            set
            {
                OnEmail01Changing(value);
                ReportPropertyChanging("Email01");
                _Email01 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email01");
                OnEmail01Changed();
            }
        }
        private global::System.String _Email01;
        partial void OnEmail01Changing(global::System.String value);
        partial void OnEmail01Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email02
        {
            get
            {
                return _Email02;
            }
            set
            {
                OnEmail02Changing(value);
                ReportPropertyChanging("Email02");
                _Email02 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email02");
                OnEmail02Changed();
            }
        }
        private global::System.String _Email02;
        partial void OnEmail02Changing(global::System.String value);
        partial void OnEmail02Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EnderecoComercial
        {
            get
            {
                return _EnderecoComercial;
            }
            set
            {
                OnEnderecoComercialChanging(value);
                ReportPropertyChanging("EnderecoComercial");
                _EnderecoComercial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EnderecoComercial");
                OnEnderecoComercialChanged();
            }
        }
        private global::System.String _EnderecoComercial;
        partial void OnEnderecoComercialChanging(global::System.String value);
        partial void OnEnderecoComercialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EnderecoResidencial
        {
            get
            {
                return _EnderecoResidencial;
            }
            set
            {
                OnEnderecoResidencialChanging(value);
                ReportPropertyChanging("EnderecoResidencial");
                _EnderecoResidencial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EnderecoResidencial");
                OnEnderecoResidencialChanged();
            }
        }
        private global::System.String _EnderecoResidencial;
        partial void OnEnderecoResidencialChanging(global::System.String value);
        partial void OnEnderecoResidencialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EstadoComercial
        {
            get
            {
                return _EstadoComercial;
            }
            set
            {
                OnEstadoComercialChanging(value);
                ReportPropertyChanging("EstadoComercial");
                _EstadoComercial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EstadoComercial");
                OnEstadoComercialChanged();
            }
        }
        private global::System.String _EstadoComercial;
        partial void OnEstadoComercialChanging(global::System.String value);
        partial void OnEstadoComercialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EstadoResidencial
        {
            get
            {
                return _EstadoResidencial;
            }
            set
            {
                OnEstadoResidencialChanging(value);
                ReportPropertyChanging("EstadoResidencial");
                _EstadoResidencial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EstadoResidencial");
                OnEstadoResidencialChanged();
            }
        }
        private global::System.String _EstadoResidencial;
        partial void OnEstadoResidencialChanging(global::System.String value);
        partial void OnEstadoResidencialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LocalAtuacao
        {
            get
            {
                return _LocalAtuacao;
            }
            set
            {
                OnLocalAtuacaoChanging(value);
                ReportPropertyChanging("LocalAtuacao");
                _LocalAtuacao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LocalAtuacao");
                OnLocalAtuacaoChanged();
            }
        }
        private global::System.String _LocalAtuacao;
        partial void OnLocalAtuacaoChanging(global::System.String value);
        partial void OnLocalAtuacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mae
        {
            get
            {
                return _Mae;
            }
            set
            {
                OnMaeChanging(value);
                ReportPropertyChanging("Mae");
                _Mae = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mae");
                OnMaeChanged();
            }
        }
        private global::System.String _Mae;
        partial void OnMaeChanging(global::System.String value);
        partial void OnMaeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Observacao
        {
            get
            {
                return _Observacao;
            }
            set
            {
                OnObservacaoChanging(value);
                ReportPropertyChanging("Observacao");
                _Observacao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Observacao");
                OnObservacaoChanged();
            }
        }
        private global::System.String _Observacao;
        partial void OnObservacaoChanging(global::System.String value);
        partial void OnObservacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pai
        {
            get
            {
                return _Pai;
            }
            set
            {
                OnPaiChanging(value);
                ReportPropertyChanging("Pai");
                _Pai = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pai");
                OnPaiChanged();
            }
        }
        private global::System.String _Pai;
        partial void OnPaiChanging(global::System.String value);
        partial void OnPaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RG
        {
            get
            {
                return _RG;
            }
            set
            {
                OnRGChanging(value);
                ReportPropertyChanging("RG");
                _RG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RG");
                OnRGChanged();
            }
        }
        private global::System.String _RG;
        partial void OnRGChanging(global::System.String value);
        partial void OnRGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RG_Expedicao
        {
            get
            {
                return _RG_Expedicao;
            }
            set
            {
                OnRG_ExpedicaoChanging(value);
                ReportPropertyChanging("RG_Expedicao");
                _RG_Expedicao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RG_Expedicao");
                OnRG_ExpedicaoChanged();
            }
        }
        private global::System.String _RG_Expedicao;
        partial void OnRG_ExpedicaoChanging(global::System.String value);
        partial void OnRG_ExpedicaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Site
        {
            get
            {
                return _Site;
            }
            set
            {
                OnSiteChanging(value);
                ReportPropertyChanging("Site");
                _Site = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Site");
                OnSiteChanged();
            }
        }
        private global::System.String _Site;
        partial void OnSiteChanging(global::System.String value);
        partial void OnSiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefone01
        {
            get
            {
                return _Telefone01;
            }
            set
            {
                OnTelefone01Changing(value);
                ReportPropertyChanging("Telefone01");
                _Telefone01 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefone01");
                OnTelefone01Changed();
            }
        }
        private global::System.String _Telefone01;
        partial void OnTelefone01Changing(global::System.String value);
        partial void OnTelefone01Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefone02
        {
            get
            {
                return _Telefone02;
            }
            set
            {
                OnTelefone02Changing(value);
                ReportPropertyChanging("Telefone02");
                _Telefone02 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefone02");
                OnTelefone02Changed();
            }
        }
        private global::System.String _Telefone02;
        partial void OnTelefone02Changing(global::System.String value);
        partial void OnTelefone02Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefone03
        {
            get
            {
                return _Telefone03;
            }
            set
            {
                OnTelefone03Changing(value);
                ReportPropertyChanging("Telefone03");
                _Telefone03 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefone03");
                OnTelefone03Changed();
            }
        }
        private global::System.String _Telefone03;
        partial void OnTelefone03Changing(global::System.String value);
        partial void OnTelefone03Changed();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="stiperModel", Name="revendedorpj")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class revendedorpj : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new revendedorpj object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static revendedorpj Createrevendedorpj(global::System.Int32 id)
        {
            revendedorpj revendedorpj = new revendedorpj();
            revendedorpj.Id = id;
            return revendedorpj;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Bairro
        {
            get
            {
                return _Bairro;
            }
            set
            {
                OnBairroChanging(value);
                ReportPropertyChanging("Bairro");
                _Bairro = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Bairro");
                OnBairroChanged();
            }
        }
        private global::System.String _Bairro;
        partial void OnBairroChanging(global::System.String value);
        partial void OnBairroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CapitalSocial
        {
            get
            {
                return _CapitalSocial;
            }
            set
            {
                OnCapitalSocialChanging(value);
                ReportPropertyChanging("CapitalSocial");
                _CapitalSocial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CapitalSocial");
                OnCapitalSocialChanged();
            }
        }
        private global::System.String _CapitalSocial;
        partial void OnCapitalSocialChanging(global::System.String value);
        partial void OnCapitalSocialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CEP
        {
            get
            {
                return _CEP;
            }
            set
            {
                OnCEPChanging(value);
                ReportPropertyChanging("CEP");
                _CEP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CEP");
                OnCEPChanged();
            }
        }
        private global::System.String _CEP;
        partial void OnCEPChanging(global::System.String value);
        partial void OnCEPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cidade
        {
            get
            {
                return _Cidade;
            }
            set
            {
                OnCidadeChanging(value);
                ReportPropertyChanging("Cidade");
                _Cidade = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cidade");
                OnCidadeChanged();
            }
        }
        private global::System.String _Cidade;
        partial void OnCidadeChanging(global::System.String value);
        partial void OnCidadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CNPJ
        {
            get
            {
                return _CNPJ;
            }
            set
            {
                OnCNPJChanging(value);
                ReportPropertyChanging("CNPJ");
                _CNPJ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CNPJ");
                OnCNPJChanged();
            }
        }
        private global::System.String _CNPJ;
        partial void OnCNPJChanging(global::System.String value);
        partial void OnCNPJChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Curriculo
        {
            get
            {
                return _Curriculo;
            }
            set
            {
                OnCurriculoChanging(value);
                ReportPropertyChanging("Curriculo");
                _Curriculo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Curriculo");
                OnCurriculoChanged();
            }
        }
        private global::System.String _Curriculo;
        partial void OnCurriculoChanging(global::System.String value);
        partial void OnCurriculoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email01
        {
            get
            {
                return _Email01;
            }
            set
            {
                OnEmail01Changing(value);
                ReportPropertyChanging("Email01");
                _Email01 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email01");
                OnEmail01Changed();
            }
        }
        private global::System.String _Email01;
        partial void OnEmail01Changing(global::System.String value);
        partial void OnEmail01Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email02
        {
            get
            {
                return _Email02;
            }
            set
            {
                OnEmail02Changing(value);
                ReportPropertyChanging("Email02");
                _Email02 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email02");
                OnEmail02Changed();
            }
        }
        private global::System.String _Email02;
        partial void OnEmail02Changing(global::System.String value);
        partial void OnEmail02Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Endereco
        {
            get
            {
                return _Endereco;
            }
            set
            {
                OnEnderecoChanging(value);
                ReportPropertyChanging("Endereco");
                _Endereco = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Endereco");
                OnEnderecoChanged();
            }
        }
        private global::System.String _Endereco;
        partial void OnEnderecoChanging(global::System.String value);
        partial void OnEnderecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IE
        {
            get
            {
                return _IE;
            }
            set
            {
                OnIEChanging(value);
                ReportPropertyChanging("IE");
                _IE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IE");
                OnIEChanged();
            }
        }
        private global::System.String _IE;
        partial void OnIEChanging(global::System.String value);
        partial void OnIEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LocalAtuacao
        {
            get
            {
                return _LocalAtuacao;
            }
            set
            {
                OnLocalAtuacaoChanging(value);
                ReportPropertyChanging("LocalAtuacao");
                _LocalAtuacao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LocalAtuacao");
                OnLocalAtuacaoChanged();
            }
        }
        private global::System.String _LocalAtuacao;
        partial void OnLocalAtuacaoChanging(global::System.String value);
        partial void OnLocalAtuacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NomeFantasia
        {
            get
            {
                return _NomeFantasia;
            }
            set
            {
                OnNomeFantasiaChanging(value);
                ReportPropertyChanging("NomeFantasia");
                _NomeFantasia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NomeFantasia");
                OnNomeFantasiaChanged();
            }
        }
        private global::System.String _NomeFantasia;
        partial void OnNomeFantasiaChanging(global::System.String value);
        partial void OnNomeFantasiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Observacao
        {
            get
            {
                return _Observacao;
            }
            set
            {
                OnObservacaoChanging(value);
                ReportPropertyChanging("Observacao");
                _Observacao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Observacao");
                OnObservacaoChanged();
            }
        }
        private global::System.String _Observacao;
        partial void OnObservacaoChanging(global::System.String value);
        partial void OnObservacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String QtdClientes
        {
            get
            {
                return _QtdClientes;
            }
            set
            {
                OnQtdClientesChanging(value);
                ReportPropertyChanging("QtdClientes");
                _QtdClientes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("QtdClientes");
                OnQtdClientesChanged();
            }
        }
        private global::System.String _QtdClientes;
        partial void OnQtdClientesChanging(global::System.String value);
        partial void OnQtdClientesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String QtdFuncionarios
        {
            get
            {
                return _QtdFuncionarios;
            }
            set
            {
                OnQtdFuncionariosChanging(value);
                ReportPropertyChanging("QtdFuncionarios");
                _QtdFuncionarios = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("QtdFuncionarios");
                OnQtdFuncionariosChanged();
            }
        }
        private global::System.String _QtdFuncionarios;
        partial void OnQtdFuncionariosChanging(global::System.String value);
        partial void OnQtdFuncionariosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RazaoSocial
        {
            get
            {
                return _RazaoSocial;
            }
            set
            {
                OnRazaoSocialChanging(value);
                ReportPropertyChanging("RazaoSocial");
                _RazaoSocial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RazaoSocial");
                OnRazaoSocialChanged();
            }
        }
        private global::System.String _RazaoSocial;
        partial void OnRazaoSocialChanging(global::System.String value);
        partial void OnRazaoSocialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RefBancaria01_Agencia
        {
            get
            {
                return _RefBancaria01_Agencia;
            }
            set
            {
                OnRefBancaria01_AgenciaChanging(value);
                ReportPropertyChanging("RefBancaria01_Agencia");
                _RefBancaria01_Agencia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RefBancaria01_Agencia");
                OnRefBancaria01_AgenciaChanged();
            }
        }
        private global::System.String _RefBancaria01_Agencia;
        partial void OnRefBancaria01_AgenciaChanging(global::System.String value);
        partial void OnRefBancaria01_AgenciaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RefBancaria01_Nome
        {
            get
            {
                return _RefBancaria01_Nome;
            }
            set
            {
                OnRefBancaria01_NomeChanging(value);
                ReportPropertyChanging("RefBancaria01_Nome");
                _RefBancaria01_Nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RefBancaria01_Nome");
                OnRefBancaria01_NomeChanged();
            }
        }
        private global::System.String _RefBancaria01_Nome;
        partial void OnRefBancaria01_NomeChanging(global::System.String value);
        partial void OnRefBancaria01_NomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RefBancaria01_Telefone
        {
            get
            {
                return _RefBancaria01_Telefone;
            }
            set
            {
                OnRefBancaria01_TelefoneChanging(value);
                ReportPropertyChanging("RefBancaria01_Telefone");
                _RefBancaria01_Telefone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RefBancaria01_Telefone");
                OnRefBancaria01_TelefoneChanged();
            }
        }
        private global::System.String _RefBancaria01_Telefone;
        partial void OnRefBancaria01_TelefoneChanging(global::System.String value);
        partial void OnRefBancaria01_TelefoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RefBancaria02_Agencia
        {
            get
            {
                return _RefBancaria02_Agencia;
            }
            set
            {
                OnRefBancaria02_AgenciaChanging(value);
                ReportPropertyChanging("RefBancaria02_Agencia");
                _RefBancaria02_Agencia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RefBancaria02_Agencia");
                OnRefBancaria02_AgenciaChanged();
            }
        }
        private global::System.String _RefBancaria02_Agencia;
        partial void OnRefBancaria02_AgenciaChanging(global::System.String value);
        partial void OnRefBancaria02_AgenciaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RefBancaria02_Nome
        {
            get
            {
                return _RefBancaria02_Nome;
            }
            set
            {
                OnRefBancaria02_NomeChanging(value);
                ReportPropertyChanging("RefBancaria02_Nome");
                _RefBancaria02_Nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RefBancaria02_Nome");
                OnRefBancaria02_NomeChanged();
            }
        }
        private global::System.String _RefBancaria02_Nome;
        partial void OnRefBancaria02_NomeChanging(global::System.String value);
        partial void OnRefBancaria02_NomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RefBancaria02_Telefone
        {
            get
            {
                return _RefBancaria02_Telefone;
            }
            set
            {
                OnRefBancaria02_TelefoneChanging(value);
                ReportPropertyChanging("RefBancaria02_Telefone");
                _RefBancaria02_Telefone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RefBancaria02_Telefone");
                OnRefBancaria02_TelefoneChanged();
            }
        }
        private global::System.String _RefBancaria02_Telefone;
        partial void OnRefBancaria02_TelefoneChanging(global::System.String value);
        partial void OnRefBancaria02_TelefoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RefComercial01_Nome
        {
            get
            {
                return _RefComercial01_Nome;
            }
            set
            {
                OnRefComercial01_NomeChanging(value);
                ReportPropertyChanging("RefComercial01_Nome");
                _RefComercial01_Nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RefComercial01_Nome");
                OnRefComercial01_NomeChanged();
            }
        }
        private global::System.String _RefComercial01_Nome;
        partial void OnRefComercial01_NomeChanging(global::System.String value);
        partial void OnRefComercial01_NomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RefComercial01_Telefone
        {
            get
            {
                return _RefComercial01_Telefone;
            }
            set
            {
                OnRefComercial01_TelefoneChanging(value);
                ReportPropertyChanging("RefComercial01_Telefone");
                _RefComercial01_Telefone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RefComercial01_Telefone");
                OnRefComercial01_TelefoneChanged();
            }
        }
        private global::System.String _RefComercial01_Telefone;
        partial void OnRefComercial01_TelefoneChanging(global::System.String value);
        partial void OnRefComercial01_TelefoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RefComercial02_Nome
        {
            get
            {
                return _RefComercial02_Nome;
            }
            set
            {
                OnRefComercial02_NomeChanging(value);
                ReportPropertyChanging("RefComercial02_Nome");
                _RefComercial02_Nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RefComercial02_Nome");
                OnRefComercial02_NomeChanged();
            }
        }
        private global::System.String _RefComercial02_Nome;
        partial void OnRefComercial02_NomeChanging(global::System.String value);
        partial void OnRefComercial02_NomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RefComercial02_Telefone
        {
            get
            {
                return _RefComercial02_Telefone;
            }
            set
            {
                OnRefComercial02_TelefoneChanging(value);
                ReportPropertyChanging("RefComercial02_Telefone");
                _RefComercial02_Telefone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RefComercial02_Telefone");
                OnRefComercial02_TelefoneChanged();
            }
        }
        private global::System.String _RefComercial02_Telefone;
        partial void OnRefComercial02_TelefoneChanging(global::System.String value);
        partial void OnRefComercial02_TelefoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Site
        {
            get
            {
                return _Site;
            }
            set
            {
                OnSiteChanging(value);
                ReportPropertyChanging("Site");
                _Site = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Site");
                OnSiteChanged();
            }
        }
        private global::System.String _Site;
        partial void OnSiteChanging(global::System.String value);
        partial void OnSiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Socio01_CPF
        {
            get
            {
                return _Socio01_CPF;
            }
            set
            {
                OnSocio01_CPFChanging(value);
                ReportPropertyChanging("Socio01_CPF");
                _Socio01_CPF = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Socio01_CPF");
                OnSocio01_CPFChanged();
            }
        }
        private global::System.String _Socio01_CPF;
        partial void OnSocio01_CPFChanging(global::System.String value);
        partial void OnSocio01_CPFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Socio01_Endereco
        {
            get
            {
                return _Socio01_Endereco;
            }
            set
            {
                OnSocio01_EnderecoChanging(value);
                ReportPropertyChanging("Socio01_Endereco");
                _Socio01_Endereco = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Socio01_Endereco");
                OnSocio01_EnderecoChanged();
            }
        }
        private global::System.String _Socio01_Endereco;
        partial void OnSocio01_EnderecoChanging(global::System.String value);
        partial void OnSocio01_EnderecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Socio01_Nome
        {
            get
            {
                return _Socio01_Nome;
            }
            set
            {
                OnSocio01_NomeChanging(value);
                ReportPropertyChanging("Socio01_Nome");
                _Socio01_Nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Socio01_Nome");
                OnSocio01_NomeChanged();
            }
        }
        private global::System.String _Socio01_Nome;
        partial void OnSocio01_NomeChanging(global::System.String value);
        partial void OnSocio01_NomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Socio02_CPF
        {
            get
            {
                return _Socio02_CPF;
            }
            set
            {
                OnSocio02_CPFChanging(value);
                ReportPropertyChanging("Socio02_CPF");
                _Socio02_CPF = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Socio02_CPF");
                OnSocio02_CPFChanged();
            }
        }
        private global::System.String _Socio02_CPF;
        partial void OnSocio02_CPFChanging(global::System.String value);
        partial void OnSocio02_CPFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Socio02_Endereco
        {
            get
            {
                return _Socio02_Endereco;
            }
            set
            {
                OnSocio02_EnderecoChanging(value);
                ReportPropertyChanging("Socio02_Endereco");
                _Socio02_Endereco = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Socio02_Endereco");
                OnSocio02_EnderecoChanged();
            }
        }
        private global::System.String _Socio02_Endereco;
        partial void OnSocio02_EnderecoChanging(global::System.String value);
        partial void OnSocio02_EnderecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Socio02_Nome
        {
            get
            {
                return _Socio02_Nome;
            }
            set
            {
                OnSocio02_NomeChanging(value);
                ReportPropertyChanging("Socio02_Nome");
                _Socio02_Nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Socio02_Nome");
                OnSocio02_NomeChanged();
            }
        }
        private global::System.String _Socio02_Nome;
        partial void OnSocio02_NomeChanging(global::System.String value);
        partial void OnSocio02_NomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefone01
        {
            get
            {
                return _Telefone01;
            }
            set
            {
                OnTelefone01Changing(value);
                ReportPropertyChanging("Telefone01");
                _Telefone01 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefone01");
                OnTelefone01Changed();
            }
        }
        private global::System.String _Telefone01;
        partial void OnTelefone01Changing(global::System.String value);
        partial void OnTelefone01Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefone02
        {
            get
            {
                return _Telefone02;
            }
            set
            {
                OnTelefone02Changing(value);
                ReportPropertyChanging("Telefone02");
                _Telefone02 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefone02");
                OnTelefone02Changed();
            }
        }
        private global::System.String _Telefone02;
        partial void OnTelefone02Changing(global::System.String value);
        partial void OnTelefone02Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefone03
        {
            get
            {
                return _Telefone03;
            }
            set
            {
                OnTelefone03Changing(value);
                ReportPropertyChanging("Telefone03");
                _Telefone03 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefone03");
                OnTelefone03Changed();
            }
        }
        private global::System.String _Telefone03;
        partial void OnTelefone03Changing(global::System.String value);
        partial void OnTelefone03Changed();

        #endregion
    
    }

    #endregion
    
}
